# Generated by Django 3.0.5 on 2020-04-04 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('covid19app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('contact', models.CharField(max_length=12)),
                ('address', models.CharField(max_length=30)),
                ('materials', models.CharField(max_length=15)),
            ],
        ),
        migrations.DeleteModel(
            name='sudent',
        ),
    ]
