# Generated by Django 3.0.5 on 2020-04-07 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('covid19app', '0002_auto_20200405_0004'),
    ]

    operations = [
        migrations.CreateModel(
            name='p_help',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('state', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=50)),
                ('district', models.CharField(max_length=50)),
                ('contact', models.CharField(max_length=12)),
                ('food', models.BooleanField(default=False)),
                ('sanitizer', models.BooleanField(default=False)),
                ('mask', models.BooleanField(default=False)),
                ('materials', models.CharField(max_length=15)),
            ],
        ),
        migrations.DeleteModel(
            name='student',
        ),
    ]
