# Generated by Django 3.0.5 on 2020-04-08 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('covid19app', '0005_ngo_list'),
    ]

    operations = [
        migrations.RenameField(
            model_name='person_help',
            old_name='mask',
            new_name='medical_supply',
        ),
        migrations.AddField(
            model_name='person_help',
            name='people',
            field=models.CharField(default=0, max_length=5),
        ),
        migrations.AlterField(
            model_name='ngo_list',
            name='contact',
            field=models.CharField(blank=True, default=None, max_length=50),
        ),
    ]
